[DEFAULT]
log_dir = /var/log/keystone

[database]
connection = mysql+pymysql://keystone:keystone@keystone-db/keystone

[token]
provider = fernet
expiration = 3600

[fernet_tokens]
key_repository = /etc/keystone/fernet-keys/

[credential]
key_repository = /etc/keystone/credential-keys/
